-d C:\Users\enthru\Desktop\DDC-receiver-Tang-Nano-9K\impl\gwsynthesis\reciever.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\enthru\Desktop\DDC-receiver-Tang-Nano-9K\src\reciever.cst
-cfg C:\Users\enthru\Desktop\DDC-receiver-Tang-Nano-9K\impl\pnr\device.cfg
-sdc C:\Users\enthru\Desktop\DDC-receiver-Tang-Nano-9K\src\reciever.sdc
-bit
-tr
-ph
-timing
-cst_error
-place_option 1
-route_option 1
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
